spring.application.name=SmartHomeEnergyManagementSystem
server.port=8082

# H2 Database Configuration (Persistent for Milestone verification)
spring.datasource.url=jdbc:h2:file:./shems_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=9a67475d459d0409382229a2101074eef6195e263255167664c1266e7418293d
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dlharini2212@gmail.com
spring.mail.password=bibgrecdjftsbczl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true